### ISSUE TITLE
 layouts, tokens and components examples 

### ISSUE THREAD

**Issue by moonbit5** [wonyoung-jang/hugo-PolyRhythmic#1]
Hi I'm just getting started with Hugo and have found this great material theme you've put together. 

Realise you're still working on documentation but could you show a few examples of how to use the elements you've created within pages, specifically _index.md and blog posts? 

For example how can the layouts, tokens and components be used in a page. Just a small example would be enough to get me started!

Thanks!

**Comment by wonyoung-jang** [comment]
Hello!

1. I would check out the running demo site: https://polyrhythmic.xyz/. The first three tabs show the tokens, layouts, and components in use.

2. Then you can find the layouts for each showcase page in the demo sites repo: https://github.com/wonyoung-jang/hugo-PolyRhythmic-demo/tree/main/layouts/showcase

3. I have not implemented any of the Material Design stuff as shortcodes, so they cannot exist on the markdown files yet, is that something that would be of interest to you? Currently, they're all layout partial templates so you'd have to specify a layout that calls those partials.

**Comment by moonbit5** [comment]
Thanks for the detailed reply! 

The demo site repo is very much what I needed. I'll dig a bit deeper and see how the partials work 

Appreciated 🙏

**Comment by wonyoung-jang** [comment]
Great! Don't hesitate to ask any more questions or to make any suggestions!
